# Laptop Price Prediction

This project aims to build a machine learning model that predicts the price of a laptop based on its specifications.

The project follows an end-to-end machine learning pipeline including data cleaning, exploratory data analysis, feature engineering, model training, evaluation, and deployment.

## 2. Objective

The objective of this project is to develop a machine learning model that can predict laptop prices based on features such as brand, processor, RAM, storage, GPU, display specifications, and other laptop characteristics.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("../data/computer_prices_all.csv")

In [9]:
df.head()

,device_type,brand,model,release_year,os,form_factor,cpu_brand,cpu_model,cpu_tier,cpu_cores,...,resolution,refresh_hz,battery_wh,charger_watts,psu_watts,wifi,bluetooth,weight_kg,warranty_months,price
0,Desktop,Samsung,Samsung Forge XDI,2022,Windows,ATX,Intel,Intel i5-11129,3,12,...,2560x1440,90,0,0,750,Wi-Fi 6,5.1,11.00,36,1383.99
1,Laptop,Samsung,Samsung Pro KM8,2022,Windows,Mainstream,Intel,Intel i7-11114,4,12,...,1920x1080,90,56,120,0,Wi-Fi 6,5.3,2.03,12,2274.99
2,Desktop,Lenovo,Lenovo Strix BIE,2024,macOS,SFF,AMD,AMD Ryzen 5 5168,2,8,...,3440x1440,120,0,0,850,Wi-Fi 6,5.0,7.00,24,1879.99
3,Desktop,Dell,Dell Cube AXR,2024,Windows,ATX,AMD,AMD Ryzen 5 7550,2,6,...,3440x1440,120,0,0,650,Wi-Fi 6,5.2,6.00,36,1331.99
4,Laptop,Gigabyte,Gigabyte Pro IX1,2024,Linux,Gaming,AMD,AMD Ryzen 7 6230,5,16,...,2560x1600,90,80,90,0,Wi-Fi 6,5.2,1.50,12,2681.99

In [10]:
df.tail()

,device_type,brand,model,release_year,os,form_factor,cpu_brand,cpu_model,cpu_tier,cpu_cores,...,resolution,refresh_hz,battery_wh,charger_watts,psu_watts,wifi,bluetooth,weight_kg,warranty_months,price
99995,Laptop,ASUS,ASUS Pro ZWL,2023,Windows,Mainstream,Intel,Intel i7-13721,4,12,...,1920x1080,144,90,180,0,Wi-Fi 6,5.1,1.87,24,1712.99
99996,Laptop,Lenovo,Lenovo Stealth 014,2018,Windows,Ultrabook,AMD,AMD Ryzen 5 5117,2,8,...,2560x1600,90,50,65,0,Wi-Fi 6,5.1,1.37,12,1258.99
99997,Laptop,ASUS,ASUS Zen LKD,2020,Windows,Mainstream,Intel,Intel i5-12677,2,6,...,2560x1600,120,99,180,0,Wi-Fi 6,4.2,1.17,12,1686.99
99998,Laptop,ASUS,ASUS Blade DH6,2020,Windows,Mainstream,AMD,AMD Ryzen 7 4590,4,12,...,2560x1600,120,60,90,0,Wi-Fi 6,5.3,1.70,24,2164.99
99999,Desktop,Acer,Acer Think L7R,2023,Windows,SFF,Intel,Intel i9-14345,6,26,...,1920x1080,144,0,0,750,Wi-Fi 6E,5.1,7.00,48,3005.99

In [5]:
df.shape

(100000, 33)

In [15]:
df.columns

Index(['device_type', 'brand', 'model', 'release_year', 'os', 'form_factor',
       'cpu_brand', 'cpu_model', 'cpu_tier', 'cpu_cores', 'cpu_threads',
       'cpu_base_ghz', 'cpu_boost_ghz', 'gpu_brand', 'gpu_model', 'gpu_tier',
       'vram_gb', 'ram_gb', 'storage_type', 'storage_gb',
       'storage_drive_count', 'display_type', 'display_size_in', 'resolution',
       'refresh_hz', 'battery_wh', 'charger_watts', 'psu_watts', 'wifi',
       'bluetooth', 'weight_kg', 'warranty_months', 'price'],
      dtype='str')

In [16]:
df.dtypes

device_type                str
brand                      str
model                      str
release_year             int64
os                         str
form_factor                str
cpu_brand                  str
cpu_model                  str
cpu_tier                 int64
cpu_cores                int64
cpu_threads              int64
cpu_base_ghz           float64
cpu_boost_ghz          float64
gpu_brand                  str
gpu_model                  str
gpu_tier                 int64
vram_gb                  int64
ram_gb                   int64
storage_type               str
storage_gb               int64
storage_drive_count      int64
display_type               str
display_size_in        float64
resolution                 str
refresh_hz               int64
battery_wh               int64
charger_watts            int64
psu_watts                int64
wifi                       str
bluetooth              float64
weight_kg              float64
warranty_months          int64
price                  float64
dtype: object

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 33 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   device_type          100000 non-null  str
 1   brand                100000 non-null  str
 2   model                100000 non-null  str
 3   release_year         100000 non-null  int64
 4   os                   100000 non-null  str
 5   form_factor          100000 non-null  str
 6   cpu_brand            100000 non-null  str
 7   cpu_model            100000 non-null  str
 8   cpu_tier             100000 non-null  int64
 9   cpu_cores            100000 non-null  int64
 10  cpu_threads          100000 non-null  int64
 11  cpu_base_ghz         100000 non-null  float64
 12  cpu_boost_ghz        100000 non-null  float64
 13  gpu_brand            100000 non-null  str
 14  gpu_model            100000 non-null  str
 15  gpu_tier             100000 non-null  int64
 16  vram_gb              100000 non-null  int64
 17  ram_gb               100000 non-null  int64
 18  storage_type         100000 non-null  str
 19  storage_gb           100000 non-null  int64
 20  storage_drive_count  100000 non-null  int64
 21  display_type         100000 non-null  str
 22  display_size_in      100000 non-null  float64
 23  resolution           100000 non-null  str
 24  refresh_hz           100000 non-null  int64
 25  battery_wh           100000 non-null  int64
 26  charger_watts        100000 non-null  int64
 27  psu_watts            100000 non-null  int64
 28  wifi                 100000 non-null  str
 29  bluetooth            100000 non-null  float64
 30  weight_kg            100000 non-null  float64
 31  warranty_months      100000 non-null  int64
 32  price                100000 non-null  float64
dtypes: float64(6), int64(14), str(13)
memory usage: 25.2 MB

In [18]:
df.nunique()

device_type                2
brand                     10
model                  99036
release_year               8
os                         4
form_factor               10
cpu_brand                  3
cpu_model              26971
cpu_tier                   6
cpu_cores                 12
cpu_threads               25
cpu_base_ghz               8
cpu_boost_ghz             18
gpu_brand                  4
gpu_model                 49
gpu_tier                   6
vram_gb                    8
ram_gb                    15
storage_type               4
storage_gb                 5
storage_drive_count        4
display_type               6
display_size_in            9
resolution                 6
refresh_hz                 6
battery_wh                 8
charger_watts              7
psu_watts                  9
wifi                       4
bluetooth                  5
weight_kg                 47
warranty_months            4
price                   3366
dtype: int64

In [11]:
df.describe()

,release_year,cpu_tier,cpu_cores,cpu_threads,cpu_base_ghz,cpu_boost_ghz,gpu_tier,vram_gb,ram_gb,storage_gb,storage_drive_count,display_size_in,refresh_hz,battery_wh,charger_watts,psu_watts,bluetooth,weight_kg,warranty_months,price
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000
mean,2022.320850,3.153490,10.515740,19.372700,2.591322,3.531310,2.991350,6.152180,39.706400,903.936000,1.524980,20.126655,98.464860,41.813470,61.383450,272.520500,5.084764,4.289699,22.20036,1928.764220
std,2.025761,1.373175,5.044092,9.718426,0.336435,0.350024,1.459643,3.964926,31.902684,774.243654,0.797284,6.709577,43.301652,35.868841,62.795034,354.686355,0.245977,3.814628,10.23190,580.492689
min,2018.000000,1.000000,4.000000,4.000000,2.000000,2.800000,1.000000,0.000000,8.000000,256.000000,1.000000,13.300000,60.000000,0.000000,0.000000,0.000000,4.200000,0.920000,12.00000,372.990000
25%,2021.000000,2.000000,6.000000,12.000000,2.400000,3.300000,2.000000,4.000000,16.000000,512.000000,1.000000,14.000000,60.000000,0.000000,0.000000,0.000000,5.000000,1.500000,12.00000,1503.990000
50%,2023.000000,3.000000,8.000000,16.000000,2.600000,3.500000,3.000000,6.000000,32.000000,512.000000,1.000000,16.000000,90.000000,56.000000,65.000000,0.000000,5.100000,2.000000,24.00000,1863.990000
75%,2024.000000,4.000000,14.000000,24.000000,2.800000,3.800000,4.000000,8.000000,64.000000,1024.000000,2.000000,27.000000,120.000000,70.000000,90.000000,650.000000,5.200000,7.000000,24.00000,2287.990000
max,2025.000000,6.000000,28.000000,56.000000,3.400000,4.500000,6.000000,16.000000,144.000000,4096.000000,4.000000,34.000000,240.000000,99.000000,240.000000,1200.000000,5.300000,16.000000,48.00000,10984.990000

In [13]:
df.describe(include="object")

/var/folders/h3/lh053x3x2tz06h7f0x583b380000gn/T/ipykernel_13691/702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,device_type,brand,model,os,form_factor,cpu_brand,cpu_model,gpu_brand,gpu_model,storage_type,display_type,resolution,wifi
count,100000,100000,100000,100000,100000,100000,100000,100000,100000,100000,100000,100000,100000
unique,2,10,99036,4,10,3,26971,4,49,4,6,6,4
top,Laptop,Lenovo,ASUS Slim R6S,Windows,Mainstream,Intel,Apple M2 Pro,NVIDIA,Apple Integrated,NVMe,LED,1920x1080,Wi-Fi 6
freq,59844,15992,3,71817,17819,52774,1389,54712,18922,45059,32000,47993,46149

In [14]:
df["device_type"].value_counts()

device_type
Laptop     59844
Desktop    40156
Name: count, dtype: int64

In [20]:

df = df[df["device_type"] == "Laptop"].copy()

In [21]:
df.shape

(59844, 33)

In [22]:
df.isnull().sum()

device_type            0
brand                  0
model                  0
release_year           0
os                     0
form_factor            0
cpu_brand              0
cpu_model              0
cpu_tier               0
cpu_cores              0
cpu_threads            0
cpu_base_ghz           0
cpu_boost_ghz          0
gpu_brand              0
gpu_model              0
gpu_tier               0
vram_gb                0
ram_gb                 0
storage_type           0
storage_gb             0
storage_drive_count    0
display_type           0
display_size_in        0
resolution             0
refresh_hz             0
battery_wh             0
charger_watts          0
psu_watts              0
wifi                   0
bluetooth              0
weight_kg              0
warranty_months        0
price                  0
dtype: int64

In [25]:
df.duplicated().sum()

np.int64(0)

In [26]:
df.columns.tolist()

['device_type',
 'brand',
 'model',
 'release_year',
 'os',
 'form_factor',
 'cpu_brand',
 'cpu_model',
 'cpu_tier',
 'cpu_cores',
 'cpu_threads',
 'cpu_base_ghz',
 'cpu_boost_ghz',
 'gpu_brand',
 'gpu_model',
 'gpu_tier',
 'vram_gb',
 'ram_gb',
 'storage_type',
 'storage_gb',
 'storage_drive_count',
 'display_type',
 'display_size_in',
 'resolution',
 'refresh_hz',
 'battery_wh',
 'charger_watts',
 'psu_watts',
 'wifi',
 'bluetooth',
 'weight_kg',
 'warranty_months',
 'price']

In [28]:
df["price"].describe()

count    59844.000000
mean      2002.051360
std        599.506201
min        372.990000
25%       1556.990000
50%       1934.990000
75%       2378.990000
max      10984.990000
Name: price, dtype: float64

In [29]:
df["brand"].value_counts()

brand
Lenovo      9507
Dell        8371
HP          8362
Apple       7130
ASUS        6093
Acer        6044
Samsung     4948
MSI         4673
Gigabyte    2875
Razer       1841
Name: count, dtype: int64

In [30]:
df["cpu_brand"].value_counts()

cpu_brand
Intel    31643
AMD      21071
Apple     7130
Name: count, dtype: int64

In [31]:
df["gpu_brand"].value_counts()

gpu_brand
NVIDIA    32745
Apple     11393
AMD        9359
Intel      6347
Name: count, dtype: int64

In [32]:
df["os"].value_counts()

os
Windows     42935
macOS       11002
Linux        3613
ChromeOS     2294
Name: count, dtype: int64